FROM bestwu/wechat

RUN apt-get update && apt-get install -y\
    sudo \
    ibus

# 设置工作目录
WORKDIR /app

# 复制文件到容器中
COPY . $HOME/WeChatFiles /WeChatFiles

# 设置环境变量
ENV DISPLAY=unix$DISPLAY \
    XMODIFIERS=@im=ibus \
    QT_IM_MODULE=ibus \
    GTK_IM_MODULE=ibus \
    AUDIO_GID=`getent group audio | cut -d: -f3` \
    GID=`id -g` \
    UID=`id -u`

# 共享主机的 X11 socket
VOLUME /tmp/.X11-unix:/tmp/.X11-unix

--ipc = host
